/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesFavoritesImport } from './routes/recipes/favorites'
import { Route as RecipesCategoryIndexImport } from './routes/recipes/$category/index'
import { Route as RecipesCategorySubcategoryIndexImport } from './routes/recipes/$category/$subcategory/index'
import { Route as RecipesCategorySubcategoryRecipeImport } from './routes/recipes/$category/$subcategory/$recipe'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesFavoritesRoute = RecipesFavoritesImport.update({
  id: '/recipes/favorites',
  path: '/recipes/favorites',
  getParentRoute: () => rootRoute,
} as any)

const RecipesCategoryIndexRoute = RecipesCategoryIndexImport.update({
  id: '/recipes/$category/',
  path: '/recipes/$category/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesCategorySubcategoryIndexRoute =
  RecipesCategorySubcategoryIndexImport.update({
    id: '/recipes/$category/$subcategory/',
    path: '/recipes/$category/$subcategory/',
    getParentRoute: () => rootRoute,
  } as any)

const RecipesCategorySubcategoryRecipeRoute =
  RecipesCategorySubcategoryRecipeImport.update({
    id: '/recipes/$category/$subcategory/$recipe',
    path: '/recipes/$category/$subcategory/$recipe',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/recipes/favorites': {
      id: '/recipes/favorites'
      path: '/recipes/favorites'
      fullPath: '/recipes/favorites'
      preLoaderRoute: typeof RecipesFavoritesImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$category/': {
      id: '/recipes/$category/'
      path: '/recipes/$category'
      fullPath: '/recipes/$category'
      preLoaderRoute: typeof RecipesCategoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$category/$subcategory/$recipe': {
      id: '/recipes/$category/$subcategory/$recipe'
      path: '/recipes/$category/$subcategory/$recipe'
      fullPath: '/recipes/$category/$subcategory/$recipe'
      preLoaderRoute: typeof RecipesCategorySubcategoryRecipeImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$category/$subcategory/': {
      id: '/recipes/$category/$subcategory/'
      path: '/recipes/$category/$subcategory'
      fullPath: '/recipes/$category/$subcategory'
      preLoaderRoute: typeof RecipesCategorySubcategoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recipes/favorites': typeof RecipesFavoritesRoute
  '/recipes/$category': typeof RecipesCategoryIndexRoute
  '/recipes/$category/$subcategory/$recipe': typeof RecipesCategorySubcategoryRecipeRoute
  '/recipes/$category/$subcategory': typeof RecipesCategorySubcategoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recipes/favorites': typeof RecipesFavoritesRoute
  '/recipes/$category': typeof RecipesCategoryIndexRoute
  '/recipes/$category/$subcategory/$recipe': typeof RecipesCategorySubcategoryRecipeRoute
  '/recipes/$category/$subcategory': typeof RecipesCategorySubcategoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recipes/favorites': typeof RecipesFavoritesRoute
  '/recipes/$category/': typeof RecipesCategoryIndexRoute
  '/recipes/$category/$subcategory/$recipe': typeof RecipesCategorySubcategoryRecipeRoute
  '/recipes/$category/$subcategory/': typeof RecipesCategorySubcategoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/logout'
    | '/recipes/favorites'
    | '/recipes/$category'
    | '/recipes/$category/$subcategory/$recipe'
    | '/recipes/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/logout'
    | '/recipes/favorites'
    | '/recipes/$category'
    | '/recipes/$category/$subcategory/$recipe'
    | '/recipes/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/login'
    | '/logout'
    | '/recipes/favorites'
    | '/recipes/$category/'
    | '/recipes/$category/$subcategory/$recipe'
    | '/recipes/$category/$subcategory/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RecipesFavoritesRoute: typeof RecipesFavoritesRoute
  RecipesCategoryIndexRoute: typeof RecipesCategoryIndexRoute
  RecipesCategorySubcategoryRecipeRoute: typeof RecipesCategorySubcategoryRecipeRoute
  RecipesCategorySubcategoryIndexRoute: typeof RecipesCategorySubcategoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RecipesFavoritesRoute: RecipesFavoritesRoute,
  RecipesCategoryIndexRoute: RecipesCategoryIndexRoute,
  RecipesCategorySubcategoryRecipeRoute: RecipesCategorySubcategoryRecipeRoute,
  RecipesCategorySubcategoryIndexRoute: RecipesCategorySubcategoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/login",
        "/logout",
        "/recipes/favorites",
        "/recipes/$category/",
        "/recipes/$category/$subcategory/$recipe",
        "/recipes/$category/$subcategory/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/recipes/favorites": {
      "filePath": "recipes/favorites.tsx"
    },
    "/recipes/$category/": {
      "filePath": "recipes/$category/index.tsx"
    },
    "/recipes/$category/$subcategory/$recipe": {
      "filePath": "recipes/$category/$subcategory/$recipe.tsx"
    },
    "/recipes/$category/$subcategory/": {
      "filePath": "recipes/$category/$subcategory/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
