/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesListRouteImport } from './routes/recipes/list'
import { Route as RecipesFavoritesRouteImport } from './routes/recipes/favorites'
import { Route as RecipesPrivateRouteImport } from './routes/recipes/_private'
import { Route as PrivateProfileRouteImport } from './routes/_private.profile'
import { Route as RecipesCategoryIndexRouteImport } from './routes/recipes/$category/index'
import { Route as RecipesPrivateAddRouteImport } from './routes/recipes/_private.add'
import { Route as RecipesCategorySubcategoryIndexRouteImport } from './routes/recipes/$category/$subcategory/index'
import { Route as RecipesCategorySubcategoryRecipeViewRouteImport } from './routes/recipes/$category/$subcategory/$recipe/view'
import { Route as RecipesCategorySubcategoryRecipePrivateRouteImport } from './routes/recipes/$category/$subcategory/$recipe/_private'
import { Route as RecipesCategorySubcategoryRecipePrivateEditRouteImport } from './routes/recipes/$category/$subcategory/$recipe/_private.edit'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesListRoute = RecipesListRouteImport.update({
  id: '/recipes/list',
  path: '/recipes/list',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesFavoritesRoute = RecipesFavoritesRouteImport.update({
  id: '/recipes/favorites',
  path: '/recipes/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesPrivateRoute = RecipesPrivateRouteImport.update({
  id: '/recipes/_private',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const RecipesCategoryIndexRoute = RecipesCategoryIndexRouteImport.update({
  id: '/recipes/$category/',
  path: '/recipes/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesPrivateAddRoute = RecipesPrivateAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => RecipesPrivateRoute,
} as any)
const RecipesCategorySubcategoryIndexRoute =
  RecipesCategorySubcategoryIndexRouteImport.update({
    id: '/recipes/$category/$subcategory/',
    path: '/recipes/$category/$subcategory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipesCategorySubcategoryRecipeViewRoute =
  RecipesCategorySubcategoryRecipeViewRouteImport.update({
    id: '/recipes/$category/$subcategory/$recipe/view',
    path: '/recipes/$category/$subcategory/$recipe/view',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipesCategorySubcategoryRecipePrivateRoute =
  RecipesCategorySubcategoryRecipePrivateRouteImport.update({
    id: '/recipes/$category/$subcategory/$recipe/_private',
    path: '/recipes/$category/$subcategory/$recipe',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipesCategorySubcategoryRecipePrivateEditRoute =
  RecipesCategorySubcategoryRecipePrivateEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RecipesCategorySubcategoryRecipePrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof PrivateProfileRoute
  '/recipes': typeof RecipesPrivateRouteWithChildren
  '/recipes/favorites': typeof RecipesFavoritesRoute
  '/recipes/list': typeof RecipesListRoute
  '/recipes/add': typeof RecipesPrivateAddRoute
  '/recipes/$category/': typeof RecipesCategoryIndexRoute
  '/recipes/$category/$subcategory/': typeof RecipesCategorySubcategoryIndexRoute
  '/recipes/$category/$subcategory/$recipe': typeof RecipesCategorySubcategoryRecipePrivateRouteWithChildren
  '/recipes/$category/$subcategory/$recipe/view': typeof RecipesCategorySubcategoryRecipeViewRoute
  '/recipes/$category/$subcategory/$recipe/edit': typeof RecipesCategorySubcategoryRecipePrivateEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof PrivateProfileRoute
  '/recipes': typeof RecipesPrivateRouteWithChildren
  '/recipes/favorites': typeof RecipesFavoritesRoute
  '/recipes/list': typeof RecipesListRoute
  '/recipes/add': typeof RecipesPrivateAddRoute
  '/recipes/$category': typeof RecipesCategoryIndexRoute
  '/recipes/$category/$subcategory': typeof RecipesCategorySubcategoryIndexRoute
  '/recipes/$category/$subcategory/$recipe': typeof RecipesCategorySubcategoryRecipePrivateRouteWithChildren
  '/recipes/$category/$subcategory/$recipe/view': typeof RecipesCategorySubcategoryRecipeViewRoute
  '/recipes/$category/$subcategory/$recipe/edit': typeof RecipesCategorySubcategoryRecipePrivateEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/recipes/_private': typeof RecipesPrivateRouteWithChildren
  '/recipes/favorites': typeof RecipesFavoritesRoute
  '/recipes/list': typeof RecipesListRoute
  '/recipes/_private/add': typeof RecipesPrivateAddRoute
  '/recipes/$category/': typeof RecipesCategoryIndexRoute
  '/recipes/$category/$subcategory/': typeof RecipesCategorySubcategoryIndexRoute
  '/recipes/$category/$subcategory/$recipe/_private': typeof RecipesCategorySubcategoryRecipePrivateRouteWithChildren
  '/recipes/$category/$subcategory/$recipe/view': typeof RecipesCategorySubcategoryRecipeViewRoute
  '/recipes/$category/$subcategory/$recipe/_private/edit': typeof RecipesCategorySubcategoryRecipePrivateEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/profile'
    | '/recipes'
    | '/recipes/favorites'
    | '/recipes/list'
    | '/recipes/add'
    | '/recipes/$category/'
    | '/recipes/$category/$subcategory/'
    | '/recipes/$category/$subcategory/$recipe'
    | '/recipes/$category/$subcategory/$recipe/view'
    | '/recipes/$category/$subcategory/$recipe/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/profile'
    | '/recipes'
    | '/recipes/favorites'
    | '/recipes/list'
    | '/recipes/add'
    | '/recipes/$category'
    | '/recipes/$category/$subcategory'
    | '/recipes/$category/$subcategory/$recipe'
    | '/recipes/$category/$subcategory/$recipe/view'
    | '/recipes/$category/$subcategory/$recipe/edit'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login'
    | '/logout'
    | '/_private/profile'
    | '/recipes/_private'
    | '/recipes/favorites'
    | '/recipes/list'
    | '/recipes/_private/add'
    | '/recipes/$category/'
    | '/recipes/$category/$subcategory/'
    | '/recipes/$category/$subcategory/$recipe/_private'
    | '/recipes/$category/$subcategory/$recipe/view'
    | '/recipes/$category/$subcategory/$recipe/_private/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RecipesPrivateRoute: typeof RecipesPrivateRouteWithChildren
  RecipesFavoritesRoute: typeof RecipesFavoritesRoute
  RecipesListRoute: typeof RecipesListRoute
  RecipesCategoryIndexRoute: typeof RecipesCategoryIndexRoute
  RecipesCategorySubcategoryIndexRoute: typeof RecipesCategorySubcategoryIndexRoute
  RecipesCategorySubcategoryRecipePrivateRoute: typeof RecipesCategorySubcategoryRecipePrivateRouteWithChildren
  RecipesCategorySubcategoryRecipeViewRoute: typeof RecipesCategorySubcategoryRecipeViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/list': {
      id: '/recipes/list'
      path: '/recipes/list'
      fullPath: '/recipes/list'
      preLoaderRoute: typeof RecipesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/favorites': {
      id: '/recipes/favorites'
      path: '/recipes/favorites'
      fullPath: '/recipes/favorites'
      preLoaderRoute: typeof RecipesFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/_private': {
      id: '/recipes/_private'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/recipes/$category/': {
      id: '/recipes/$category/'
      path: '/recipes/$category'
      fullPath: '/recipes/$category/'
      preLoaderRoute: typeof RecipesCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/_private/add': {
      id: '/recipes/_private/add'
      path: '/add'
      fullPath: '/recipes/add'
      preLoaderRoute: typeof RecipesPrivateAddRouteImport
      parentRoute: typeof RecipesPrivateRoute
    }
    '/recipes/$category/$subcategory/': {
      id: '/recipes/$category/$subcategory/'
      path: '/recipes/$category/$subcategory'
      fullPath: '/recipes/$category/$subcategory/'
      preLoaderRoute: typeof RecipesCategorySubcategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$category/$subcategory/$recipe/view': {
      id: '/recipes/$category/$subcategory/$recipe/view'
      path: '/recipes/$category/$subcategory/$recipe/view'
      fullPath: '/recipes/$category/$subcategory/$recipe/view'
      preLoaderRoute: typeof RecipesCategorySubcategoryRecipeViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$category/$subcategory/$recipe/_private': {
      id: '/recipes/$category/$subcategory/$recipe/_private'
      path: '/recipes/$category/$subcategory/$recipe'
      fullPath: '/recipes/$category/$subcategory/$recipe'
      preLoaderRoute: typeof RecipesCategorySubcategoryRecipePrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$category/$subcategory/$recipe/_private/edit': {
      id: '/recipes/$category/$subcategory/$recipe/_private/edit'
      path: '/edit'
      fullPath: '/recipes/$category/$subcategory/$recipe/edit'
      preLoaderRoute: typeof RecipesCategorySubcategoryRecipePrivateEditRouteImport
      parentRoute: typeof RecipesCategorySubcategoryRecipePrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateProfileRoute: typeof PrivateProfileRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateProfileRoute: PrivateProfileRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface RecipesPrivateRouteChildren {
  RecipesPrivateAddRoute: typeof RecipesPrivateAddRoute
}

const RecipesPrivateRouteChildren: RecipesPrivateRouteChildren = {
  RecipesPrivateAddRoute: RecipesPrivateAddRoute,
}

const RecipesPrivateRouteWithChildren = RecipesPrivateRoute._addFileChildren(
  RecipesPrivateRouteChildren,
)

interface RecipesCategorySubcategoryRecipePrivateRouteChildren {
  RecipesCategorySubcategoryRecipePrivateEditRoute: typeof RecipesCategorySubcategoryRecipePrivateEditRoute
}

const RecipesCategorySubcategoryRecipePrivateRouteChildren: RecipesCategorySubcategoryRecipePrivateRouteChildren =
  {
    RecipesCategorySubcategoryRecipePrivateEditRoute:
      RecipesCategorySubcategoryRecipePrivateEditRoute,
  }

const RecipesCategorySubcategoryRecipePrivateRouteWithChildren =
  RecipesCategorySubcategoryRecipePrivateRoute._addFileChildren(
    RecipesCategorySubcategoryRecipePrivateRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RecipesPrivateRoute: RecipesPrivateRouteWithChildren,
  RecipesFavoritesRoute: RecipesFavoritesRoute,
  RecipesListRoute: RecipesListRoute,
  RecipesCategoryIndexRoute: RecipesCategoryIndexRoute,
  RecipesCategorySubcategoryIndexRoute: RecipesCategorySubcategoryIndexRoute,
  RecipesCategorySubcategoryRecipePrivateRoute:
    RecipesCategorySubcategoryRecipePrivateRouteWithChildren,
  RecipesCategorySubcategoryRecipeViewRoute:
    RecipesCategorySubcategoryRecipeViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
