/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/auth'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CategoryIdIndexImport } from './routes/$categoryId/index'
import { Route as CategoryIdSubcategoryIdIndexImport } from './routes/$categoryId/$subcategoryId/index'
import { Route as CategoryIdSubcategoryIdRecipeIdImport } from './routes/$categoryId/$subcategoryId/$recipeId'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CategoryIdIndexRoute = CategoryIdIndexImport.update({
  id: '/$categoryId/',
  path: '/$categoryId/',
  getParentRoute: () => rootRoute,
} as any)

const CategoryIdSubcategoryIdIndexRoute =
  CategoryIdSubcategoryIdIndexImport.update({
    id: '/$categoryId/$subcategoryId/',
    path: '/$categoryId/$subcategoryId/',
    getParentRoute: () => rootRoute,
  } as any)

const CategoryIdSubcategoryIdRecipeIdRoute =
  CategoryIdSubcategoryIdRecipeIdImport.update({
    id: '/$categoryId/$subcategoryId/$recipeId',
    path: '/$categoryId/$subcategoryId/$recipeId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/$categoryId/': {
      id: '/$categoryId/'
      path: '/$categoryId'
      fullPath: '/$categoryId'
      preLoaderRoute: typeof CategoryIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/$categoryId/$subcategoryId/$recipeId': {
      id: '/$categoryId/$subcategoryId/$recipeId'
      path: '/$categoryId/$subcategoryId/$recipeId'
      fullPath: '/$categoryId/$subcategoryId/$recipeId'
      preLoaderRoute: typeof CategoryIdSubcategoryIdRecipeIdImport
      parentRoute: typeof rootRoute
    }
    '/$categoryId/$subcategoryId/': {
      id: '/$categoryId/$subcategoryId/'
      path: '/$categoryId/$subcategoryId'
      fullPath: '/$categoryId/$subcategoryId'
      preLoaderRoute: typeof CategoryIdSubcategoryIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$categoryId': typeof CategoryIdIndexRoute
  '/$categoryId/$subcategoryId/$recipeId': typeof CategoryIdSubcategoryIdRecipeIdRoute
  '/$categoryId/$subcategoryId': typeof CategoryIdSubcategoryIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$categoryId': typeof CategoryIdIndexRoute
  '/$categoryId/$subcategoryId/$recipeId': typeof CategoryIdSubcategoryIdRecipeIdRoute
  '/$categoryId/$subcategoryId': typeof CategoryIdSubcategoryIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$categoryId/': typeof CategoryIdIndexRoute
  '/$categoryId/$subcategoryId/$recipeId': typeof CategoryIdSubcategoryIdRecipeIdRoute
  '/$categoryId/$subcategoryId/': typeof CategoryIdSubcategoryIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/login'
    | '/logout'
    | '/$categoryId'
    | '/$categoryId/$subcategoryId/$recipeId'
    | '/$categoryId/$subcategoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/login'
    | '/logout'
    | '/$categoryId'
    | '/$categoryId/$subcategoryId/$recipeId'
    | '/$categoryId/$subcategoryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/login'
    | '/logout'
    | '/$categoryId/'
    | '/$categoryId/$subcategoryId/$recipeId'
    | '/$categoryId/$subcategoryId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  CategoryIdIndexRoute: typeof CategoryIdIndexRoute
  CategoryIdSubcategoryIdRecipeIdRoute: typeof CategoryIdSubcategoryIdRecipeIdRoute
  CategoryIdSubcategoryIdIndexRoute: typeof CategoryIdSubcategoryIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  CategoryIdIndexRoute: CategoryIdIndexRoute,
  CategoryIdSubcategoryIdRecipeIdRoute: CategoryIdSubcategoryIdRecipeIdRoute,
  CategoryIdSubcategoryIdIndexRoute: CategoryIdSubcategoryIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/auth",
        "/login",
        "/logout",
        "/$categoryId/",
        "/$categoryId/$subcategoryId/$recipeId",
        "/$categoryId/$subcategoryId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/$categoryId/": {
      "filePath": "$categoryId/index.tsx"
    },
    "/$categoryId/$subcategoryId/$recipeId": {
      "filePath": "$categoryId/$subcategoryId/$recipeId.tsx"
    },
    "/$categoryId/$subcategoryId/": {
      "filePath": "$categoryId/$subcategoryId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
